import '@/styles/globals.css'
import Layout from '@/components/Layout'
import Head from 'next/head'

export default function App({ Component, pageProps }) {

  if (Component.getLayout) {
    return Component.getLayout(<Component {...pageProps} />)
  }

  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/dan-profile.jpg" />
      </Head>
    
      <Layout criteria={true}>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}
